language: node_js
node_js: stable
# assign build branches
branches:
  only:
  - MeteoBoy4

before_install:
  - openssl aes-256-cbc -K $encrypted_833893b153a0_key -iv $encrypted_833893b153a0_iv -in id_rsa.enc -out id_rsa -d 
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - cd ..
  - git clone --depth=50 --branch=source https://github.com/MeteoBoy4/MeteoBoy4.github.io.git
  - cd MeteoBoy4.github.io
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive --remote
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo generate --silent

after_success:
  - git config --global user.name "MeteoBoy4"
  - git config --global user.email "lichiqin4@gmail.com"
#  - sed -i” “/^ *repo/s~github\.com~${githubToken}@github.com~” _config.yml
  - hexo deploy

# E: Build LifeCycle
